# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  rayboing_config = debug
  raylib_config = debug
endif
ifeq ($(config),release)
  rayboing_config = release
  raylib_config = release
endif

PROJECTS := rayboing raylib level_launcher

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

rayboing: raylib
ifneq (,$(rayboing_config))
	@echo "==== Building rayboing ($(rayboing_config)) ===="
	@${MAKE} --no-print-directory -C build_files -f rayboing.make config=$(rayboing_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C build_files -f raylib.make config=$(raylib_config)
endif

level_launcher: rayboing
	@echo "==== Building level_launcher ===="
	@g++ -std=c++17 src/level_launcher.cpp -o bin/Debug/level_launcher
	@echo "==== level_launcher build complete ===="

clean:
	@${MAKE} --no-print-directory -C build_files -f rayboing.make clean
	@${MAKE} --no-print-directory -C build_files -f raylib.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   rayboing"
	@echo "   raylib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"